version: "3.8"

services:
  mongodb:
    image: mongo:4.2.11
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: getnet
      MONGO_INITDB_ROOT_PASSWORD: getnet

networks:
  webhook-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24
